name: tichu_server
description: WebSocket server for multiplayer Tichu games
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  uuid: ^4.2.1
  tichu_engine:
    path: /packages/tichu_engine

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
